# Site settings
title:       Rahul's Blog
email:       rahulrevo@gmail.com
author:      Rahul Revo
description: "Personal Blog"
baseurl:     ""
url:         "http://rrevo.github.io"

# Google analytics
google_analytics: 'UA-50541441-1'

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: rrevo
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: rrevo
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
